### ISSUE TITLE
Problem after changing paths

### ISSUE THREAD

**Issue by timmermansjoy** [Morzomb/All-jellyfin-media-server#13]
Hey there again. 

I tested out my setup and worked fine and then I added a drive to the machine and moved everything onto there. I currently have

```docker
version: "3.8"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}:${OUT_PATH}
      - ${COMMON_PATH}/configs/qbittorrent:/config
      - ${COMMON_PATH}/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}/configs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}:${OUT_PATH}
      - ${COMMON_PATH}/configs/sonarr:/config
      - ${COMMON_PATH}/sonarr/tv:/tv
      - ${COMMON_PATH}/qbittorrent/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}:${OUT_PATH}
      - ${COMMON_PATH}/configs/radarr:/config
      - ${COMMON_PATH}/radarr/movies:/movies
      - ${COMMON_PATH}/qbittorrent/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ${COMMON_PATH}:${OUT_PATH}
      - ${COMMON_PATH}/configs/jellyfin:/config
      - ${COMMON_PATH}/jellyfin/cache:/cache
      - ${COMMON_PATH}/sonarr/tv:/data/tvshows
      - ${COMMON_PATH}/radarr/movies:/data/movies
      - ${COMMON_PATH}/qbittorrent/downloads:/data/media_downloads
    devices:
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mali0:/dev/mali0
      - /dev/rga:/dev/rga
      - /dev/mpp_service:/dev/mpp_service
      - /dev/iep:/dev/iep
      - /dev/mpp-service:/dev/mpp-service
      - /dev/vpu_service:/dev/vpu_service
      - /dev/vpu-service:/dev/vpu-service
      - /dev/hevc_service:/dev/hevc_service
      - /dev/hevc-service:/dev/hevc-service
      - /dev/rkvdec:/dev/rkvdec
      - /dev/rkvenc:/dev/rkvenc
      - /dev/vepu:/dev/vepu
      - /dev/h265e:/dev/h265e
    restart: unless-stopped
    privileged: true

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${COMMON_PATH}/configs/jellyseerr:/app/config
    restart: unless-stopped
```

and 

```bash
PUID=1000
PGID=1000
COMMON_PATH=/storage/media
OUT_PATH=/home/joy/media-server/storage
TZ=Europe/Brussels
```

as config. 

I changed the containers to have a OUT_PATH aswell so that it would not give any conflicts with any of the config files or so that have paths set. but I just cant get it to work. it seems like it creates the folders but it does not mount them correctly or so where the stuff inside the folders, the movies is just not getten shown if I do `docker exec -it radarr bash` for instance and then do a ls on /movies. I dont see what I'm doing wrong. I'm looking for this now for a whole day with no results. any suggestions?

**Comment by Morzomb** [comment]
Hello @timmermansjoy,

I tested your setup, and it’s quite good. I like the idea of having a path that can be different both on the server and inside the Docker container.

Regarding your issue, after testing your setup, I encountered only one error. I believe this is where your problem comes from: it concerns the PUID and PGID. You’ve set them to 1000. As a result, when adding the Root Folders, I encountered a permissions error. This means that your Docker containers will never have the necessary permissions to write to the folders.

![image](https://github.com/user-attachments/assets/f5bc863c-8109-4df9-a490-cc496f782e79)

So, I simply changed your PUID and PGID to root. Like this :

```.env
PUID = 0
PGID = 0
```

After changing the privileges, I was able to add the path and download, and Radarr did its job :

![image](https://github.com/user-attachments/assets/7595b2cf-6478-42cd-b7b3-2d93f8dda95a)

## On the server :
![image](https://github.com/user-attachments/assets/3ff99e91-071d-4855-bf2e-283c4f659dc9)

## Inside the container :
![image](https://github.com/user-attachments/assets/436dddff-5071-408a-ac80-b51d3e13fa2f)

## In Radarr :
![image](https://github.com/user-attachments/assets/92e34141-8d3e-401a-ad86-487cc1cda307)

**Comment by timmermansjoy** [comment]
Thanks for your response. 

on your first note. the out_path is actually a workaround, around a flawed structre. you already map everything on root level. like the `radarr/movies` get mounted on `/movies` the `config/radarr` gets mounted on `/config` so you actually should just use those paths (they are not in your tutorial markdown) instead of having a `-${COMMON_PATH}:${OUT_PATH}` This way it becomes more portable if you would ever change your `COMMON_PATH` like I did. 

## My issue

I should be more clearer and just typed it out too quickly. I have a location that I previously used on a small drive that also still works. what I then did was do a `cp` command more precisely a `rsync` command to copy all the files to a bigger mounted storage. This has been successful and I also manually verified this 10x and even did it again to be sure. I then checked to make sure that all of the directories have the correct pid and they 100% do have it from the root /storage to every single child of that. 

However when I do a `docker compose up` it seems like it is mounting somewhere else. I have to make new logins again for Sonarr, radarr, Jellyfin, etc etc. When I do make a new account and do docker compose down and back up it still stores those new settings. And I cant seem to find these changes reflected anywhere on my device. its absolutely crazy and I cant find a solution

**Comment by timmermansjoy** [comment]
omfg.... it was because docker was installed via snap and then it does not have the correct permissions...
