### ISSUE TITLE
Structure question

### ISSUE THREAD

**Issue by timmermansjoy** [Morzomb/All-jellyfin-media-server#8]
Hi I was looking for a good start for a project like this. However I have a question surrounding the indexers. 

This project both uses Jackett and Prowlarr for indexers. However is this not overcomplicating it and should you not just leave Jackett out of it and just use prowlerr to setup your indexers and then sync them to both Radarr and Sonarr instead of setting them up manually?

**Comment by Morzomb** [comment]
Hello @timmermansjoy,

Indeed, it’s not necessarily required to use Jackett. However, in my case, I’ve had several instances where Prowlarr stopped performing searches on the indexers. That’s why I added Jackett. While it does make synchronization with Sonarr and Radarr a bit more complex, Jackett still provides added value in those situations. That said, configuring Jackett is entirely optional.
